// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAifiubCzUiqPd1PI1-BF10io692Cy_IqA',
    appId: '1:850709853544:web:b42430230b571b48d5d2dd',
    messagingSenderId: '850709853544',
    projectId: 'my-smart-campus-app-b4ff2',
    authDomain: 'my-smart-campus-app-b4ff2.firebaseapp.com',
    storageBucket: 'my-smart-campus-app-b4ff2.firebasestorage.app',
    measurementId: 'G-Q0MWP45NRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4xATasBMQtJ9g4LahQkiJGOy15TEcs3M',
    appId: '1:850709853544:android:4db007a89cb9d44fd5d2dd',
    messagingSenderId: '850709853544',
    projectId: 'my-smart-campus-app-b4ff2',
    storageBucket: 'my-smart-campus-app-b4ff2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmvX0218QM2uf3RM97ezZXcEVbSKZ0uYc',
    appId: '1:850709853544:ios:2a98e407f936a974d5d2dd',
    messagingSenderId: '850709853544',
    projectId: 'my-smart-campus-app-b4ff2',
    storageBucket: 'my-smart-campus-app-b4ff2.firebasestorage.app',
    iosBundleId: 'com.example.flutterSmartCampus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmvX0218QM2uf3RM97ezZXcEVbSKZ0uYc',
    appId: '1:850709853544:ios:2a98e407f936a974d5d2dd',
    messagingSenderId: '850709853544',
    projectId: 'my-smart-campus-app-b4ff2',
    storageBucket: 'my-smart-campus-app-b4ff2.firebasestorage.app',
    iosBundleId: 'com.example.flutterSmartCampus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAifiubCzUiqPd1PI1-BF10io692Cy_IqA',
    appId: '1:850709853544:web:4d74a54dfbb7449ed5d2dd',
    messagingSenderId: '850709853544',
    projectId: 'my-smart-campus-app-b4ff2',
    authDomain: 'my-smart-campus-app-b4ff2.firebaseapp.com',
    storageBucket: 'my-smart-campus-app-b4ff2.firebasestorage.app',
    measurementId: 'G-MRF77LDK2C',
  );
}
